try:
    welt_retten()
finally: # wird immer ausgefuehrt auch wenn eine unbekannte exception eintrifft
    print('Dinge, die so oder so gemacht werden muessen.')
